ranking paper
Bibliko/Stock_Project pull request #84
Opened 2020-10-06 17:15 UTC by anhthu2003

2020-10-06 20:21 UTC, doanhtu07 requested changes
Bà chưa bỏ cái Paper này vào LandingPage trong src/pages/Main/LandingPage. Bà phải bỏ vào để tui xem trên trang chính nó nhìn như nào.

2020-10-06 20:21 UTC, doanhtu07 commented on front-end/src/components/Landing Page Papers/RakingPaper.js
> +                        {this.showRanking(overall)}
showRanking là hàm gì vậy bà?

2020-10-08 17:21 UTC, doanhtu07 requested changes
Bạn phải đảm bảo code bạn chạy trên web trước nha. Code hiện tại có lỗi và không chạy được.

2020-10-08 17:21 UTC, doanhtu07 commented on front-end/src/components/Paper/LandingPage/RankingPaper.js
> +        color='#9ED2EF',
Bạn vẫn chưa sửa lỗi này

2020-10-08 17:21 UTC, doanhtu07 commented on front-end/src/components/Paper/LandingPage/RankingPaper.js
> +    const [selectedTab, setSelectedTab] = React.useState(0);
Cái này hông chạy được trong class. Mình có nói cái cách viết này là cho function chứ không phải class.

2020-10-08 17:21 UTC, doanhtu07 commented on front-end/src/components/Paper/LandingPage/RankingPaper.js
> +    const handleChange = (event, newSelectedTab) => {
Class không có chữ const đằng đầu

2020-10-26 05:10 UTC, doanhtu07 requested changes
- Đổi màu cái thanh navbar của RankingPaper của bà thành #141466
- Sao RankingPaper vẫn chưa có data nào display lên đấy?

2020-10-26 05:10 UTC, doanhtu07 commented on front-end/src/components/Paper/LandingPage/RankingPaper.js
> +  selectedTab: PropTypes.any.isRequired,
Đổi selectedTab thành value

2020-10-26 05:10 UTC, doanhtu07 commented on front-end/src/components/Paper/LandingPage/RankingPaper.js
> +      console.log(top8UsersOnPage1);
Xoá console log không cần thiết.

2020-10-26 05:10 UTC, doanhtu07 commented on front-end/src/components/Paper/LandingPage/RankingPaper.js
> +      console.log(top8UsersOnPage1);
Xoá console log không cần thiết.

2020-10-26 05:10 UTC, doanhtu07 commented on front-end/src/components/Paper/LandingPage/RankingPaper.js
> +    const region = this.state;
Cái này là sao đây bạn? region trong state bạn đã dùng để store array. Cái region để bỏ vào dùng cho API phải là string. Ví dụ như "Asia." List các region mà mình đang dùng bạn có thể vào Account Settings xem.

2021-05-29 09:22 UTC, thuyettiensinh commented on front-end/src/pages/Main/HomePage.js
>      //maxHeight: '300px'
Should remove this

2021-05-29 09:23 UTC, thuyettiensinh commented on front-end/src/pages/Main/Ranking.js
> +      portfolioValue,
Xóa space bị thừa

2021-05-29 09:49 UTC, thuyettiensinh commented on front-end/src/utils/UserUtil.js
> +export const getOverallRanking = (
Chỗ này không có nhiều param cũng chưa bị quá số cột thì không nên xuống dòng
`export const getOverallRanking = (page) = {`

2021-05-29 09:50 UTC, thuyettiensinh commented on front-end/src/utils/UserUtil.js
> +export const getRegionalRanking = (
same above

2021-07-22 03:53 UTC, Legacy107 approved these changes
LGTM!

2021-07-22 03:57 UTC, merged