User overall ranking
Bibliko/Stock_Project pull request #87
Opened 2020-10-10 23:29 UTC by mqluu02

Display user overall ranking

2020-10-12 03:42 UTC, doanhtu07 requested changes
- Sửa các lỗi em nói
- Sau đó, anh xem cái this.chooseTableRow("1" ...) rồi 2 rồi 3 gần cuối file Table/RankingTable/OverallTable.js
Anh hãy viết this.state.userRanking.map(user => this.chooseTableRow(user, classes));

2020-10-12 03:42 UTC, doanhtu07 commented on front-end/src/components/Table/RankingTable/OverallTable.js
> +    }).then(result=>this.setState({userRanking: result.data})).catch(error=>console.log(error))
Sửa chữ result thành overallRankingData

2020-10-12 03:42 UTC, doanhtu07 commented on front-end/src/components/Table/RankingTable/OverallTable.js
> +  state= {userRanking: []};
sửa cái userRanking thành overallRanking

2020-10-12 03:42 UTC, doanhtu07 commented on front-end/src/components/Table/RankingTable/OverallTable.js
>    chooseTableRow = (type, classes) => {
Anh hãy thiết kế cái chooseTableRow này làm sao mà có thể dùng display chung chứ đừng dùng if else. 
Chẳng hạn mỗi user đều có tên, portfolio, region thì anh viết chooseTableRow nhận vào một cái object user chẳng hạn. Xong anh display thông tin user.firstName + user.lastName, user.portfolio, user.region.

2020-10-18 20:06 UTC, doanhtu07 requested changes
- Xoá hết mấy cái console log không cần thiết. Em thấy nhiều log quá.

2020-10-18 20:06 UTC, doanhtu07 commented on front-end/src/components/Table/RankingTable/OverallTable.js
>    chooseTableRowValue = (type) => {
Function này không có ý nghĩa

2020-10-18 20:06 UTC, doanhtu07 commented on front-end/src/components/Table/RankingTable/OverallTable.js
>    chooseTableRow = (type, classes) => {
Anh vẫn dùng if else, lặp cục code lớn quá. Anh có thể dùng cách viết { condition? value1 : value2 } thay vì dùng if else

2020-10-18 20:06 UTC, doanhtu07 commented on front-end/src/components/Table/RankingTable/OverallTable.js
> +            {this.chooseTableRow(1, classes)}
Anh vẫn chưa dùng loop giống em nói. 
this.state.overallRanking.map(user => (
      this.chooseTableRow(...)
));
Kiểu thế. Anh viết code gọn nhất có thể nha là được.

2020-10-18 20:06 UTC, doanhtu07 commented on front-end/src/components/Table/RankingTable/OverallTable.js
> +        >{currentUser.firstName}</TableCell>
Với cái này display name chứ không phải firstName không. Name là first name + last name. Anh sửa nguyên cột này thành name hết.

2021-07-21 15:26 UTC, Legacy107 approved these changes
LGTM!

2021-07-21 15:27 UTC, merged